#ifndef CONSTANTS_H_INCLUDED
#define CONSTANTS_H_INCLUDED

#define ESCAPE_KEY 27
#define LEFT_ARROW_KEY 100
#define RIGHT_ARROW_KEY 102

#define PIXELS_PER_CM 1.0
#define PIXELS_PER_METER (PIXELS_PER_CM * 100.0)

#define BALL_RADIUS_CM (4.28/2.0)
#define BALL_RADIUS_PX (BALL_RADIUS_CM * PIXELS_PER_CM)

#define HOLE_RADIUS_CM (10.795/2.0)
#define HOLE_RADIUS_PX (HOLE_RADIUS_CM * PIXELS_PER_CM)

#define BALL_DETAIL_LEVEL 12
#define HOLE_DETAIL_LEVEL 24

#define TARGET_FPS 60.0

#define FRICTION 5.0
#define SPEED_LOST_ON_WALL_IMPACT 0.67

#define BAR_SPEED 0.01f
#define CAMERA_ROTATION_SPEED 60.0
#define ARROW_ROTATION_SPEED 40.0

extern const int INIT_WINDOW_SIZE_X;
extern const int INIT_WINDOW_SIZE_Y;
extern const int INIT_WINDOW_POS_X;
extern const int INIT_WINDOW_POS_Y;
extern const char * WINDOW_TITLE;
extern const int PERSPECTIVE_FOV;
extern const float PERSPECTIVE_NEAR;
extern const float PERSPECTIVE_FAR;

#endif // CONSTANTS_H_INCLUDED
